# Generated by Django 4.0 on 2021-12-23 21:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('avaliacao', models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Avaliação')),
            ],
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('arte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.arte')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem')),
            ],
            bases=('app.arte',),
        ),
        migrations.CreateModel(
            name='Poesia',
            fields=[
                ('arte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.arte')),
                ('corpo', models.TextField()),
            ],
            bases=('app.arte',),
        ),
    ]
