# Generated by Django 4.0 on 2021-12-23 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='avaliacao',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Avaliação'),
        ),
    ]
